Jela svijeta

<table>
    <thead>
        <tr>
            <th>Jela</th>
            <th>Kategorija</th>
            <th>Tag</th>
            <th>Sastojci</th>
        </tr>
    </thead>
    <?php foreach($jela as $j): ?>
            <tr>
                <td><?=$j->naziv?></td>
                <td><?=$j->kategorija?></td>
                <td><?=$j->tag?></td>
                <td><?=$j->sastojak?></td>
                <td><?php Log::log($j->sastojciujelima); ?>
                <?php foreach($j->sastojciujelima as $s){
                        Log::log($s);
                        echo $sastojak;
                }
                ?></td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>

