
<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <head>
    <?php include_once 'templates/head.phtml'; ?>
  </head>
<body>
    <?php include_once 'templates/navbar.phtml' ?>
 
    <div class="grid-container">
      <div class="grid-x grid-padding-x">
        <div class="large-12 cell">
          <?php echo $contentView; ?>
        </div>
      </div>
    </div>

    <div class="footing">
        <?php include_once 'templates/footing.phtml'; ?>
    </div>

   <?php include_once 'templates/scripts.phtml'; ?>
  </body>
</html>
