<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="example-menu"></button>
  <div class="title-bar-title"><?php echo App::config('nameApp'); ?></div>
</div>

<div class="top-bar" id="example-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text"><a class="appname" href="<?php echo App::config('url'); ?>"><?php echo App::config('nameApp'); ?></a></li>
      <li><a href="<?php echo App::config('url')?>jela">Jelovnik</a></li>
      <li><a href="<?php echo App::config('url')?>kategorije">Kategorije</a></li>
      <li><a href="<?php echo App::config('url')?>tags">Tags</a></li>
      <li><a href="<?php echo App::config('url')?>sastojci">Sastojci</a></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="dropdown menu" data-dropdown-menu>
      <li>
        <a href="#">Jezik</a>
        <ul class="menu vertical">
          <li><a href="<?php echo App::config('url')?>jela">Hrv</a></li>
          <li><a href="<?php echo App::config('url')?>jelaeng">Eng</a></li>
          <li><a href="#">De</a></li>
        </ul>
      </li>
    </ul>
  </div>
</div>